Resolve typescript error The following typescript error is no longer reported when running `npm run typecheck`
src/util/web_worker_transfer.ts:114:9 - error TS2322: Type 'unknown' is
not assignable to type 'Serialized'.

114         return input;